### PR TITLE
ISSUE-1080 CalendarEvent/accept a missing method ics should not return serverFail

### LINKED ISSUE #1080: Cannot invoke \"net.fortuna.ical4j.model.property.Method.getValue()\" because the return value of \"net.fortuna.ical4j.model.Calendar.getMethod()\" is null
### Description of the bug

server-fail :red_circle: 

### Reproduction Steps

[Calendar invite.ics.txt](https://github.com/user-attachments/files/15514571/Calendar.invite.ics.txt)

### Expected result

I expect a nicer method level failure.

### Definition of done

Explicit tests with this ICS...

[Calendar invite.ics.txt](https://github.com/user-attachments/files/15515080/Calendar.invite.ics.txt)

### PR DESCRIPTION
**Pull request by quantranhong1999**
resolve #1080

### CODE REVIEW

File: tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventAcceptMethodContract.scala [hunk 1]
```diff
@@ -86,6 +86,178 @@ trait LinagoraCalendarEventAcceptMethodContract {
...
+
+    assertThatJson(response)
+      .withOptions(new Options(IGNORING_ARRAY_ORDER))
+      .inPath("methodResponses[0]")
+      .isEqualTo(
+        s"""[
+           |    "CalendarEvent/accept",
+           |    {
+           |        "accountId": "$ACCOUNT_ID",
+           |        "notAccepted": [ "$missingVEventIcsBlobId" ]
```
Comment (chibenwa) [inline tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventAcceptMethodContract.scala:255]: Wrong format here.

We shall have details of the problems in there...

image

Please update the code, tests, documentation in order to match the syntax of `Email/set notUpdated`....

**Review by Arsnael — COMMENTED** [review]
Read it nothing to add

**Review by chibenwa — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]
