### PR TITLE
ISSUE-741 Auto-complete for team mailboxes

### LINKED ISSUE #741: Auto-complete for team mailboxes
### Description of the bug

Today given I write for the first time a mail for cosoft-barcamp@linagora.com team mailbox, then no auto-completion result is proposed.

### Reproduction Steps

Send a mail to a team mailbox

### Expected result

I expect a search result to be proposed for existing team mailboxes.

Simply add the team mailbox into domain contacts after creation.

### Context

tmail.linagora.com

### PR DESCRIPTION
**Pull request by quantranhong1999**
resolve #741

### CODE REVIEW

File: tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala [hunk 1]
```diff
@@ -2821,6 +2821,63 @@ trait TeamMailboxesContract {
...
+         |      "filter": {"text":"hiring"}
+         |    },
+         |    "c1"]]
+         |}""".stripMargin
+
+    val response =  `given`
+      .header(ACCEPT.toString, ACCEPT_RFC8621_VERSION_HEADER)
+      .body(bobRequest)
+    .when
+      .post.prettyPeek()
```
Comment (Arsnael) [inline tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala:2858]: Debug spotted

**Review by Arsnael — APPROVED** [review]
Just a small comment, otherwise looks good :)

File: tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala [hunk 2]
```diff
@@ -2756,6 +2767,117 @@ trait TeamMailboxesContract {
...
```
Comment (quantranhong1999) [inline tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/TeamMailboxesContract.scala:2858]:
```suggestion
      .post
```

**Review by Arsnael — APPROVED** [review]

**Review by vttranlina — APPROVED** [review]

File: tmail-backend/webadmin/webadmin-team-mailboxes/src/main/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutes.java [hunk 3]
```diff
@@ -142,7 +151,10 @@ public Route addTeamMailbox() {
                     .haltError();
             }
 
-            return Mono.from(teamMailboxRepository.createTeamMailbox(new TeamMailbox(domain, teamMailboxName)))
+            TeamMailbox teamMailbox = new TeamMailbox(domain, teamMailboxName);
+
+            return Mono.from(teamMailboxRepository.createTeamMailbox(teamMailbox))
+                .then(Mono.from(contactSearchEngine.index(domain, new ContactFields(teamMailbox.asMailAddress(), teamMailboxName.asString(), ""))))
```
Comment (chibenwa) [inline tmail-backend/webadmin/webadmin-team-mailboxes/src/main/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutes.java:157]: Please do not leak logic in the presentation layer, this is a clearly wrong design pattern.

If later we add another way to add team mailboxes then the code will be duplicated at best. At worst we will have a bug.

We need IMO a generic way to extend the behavior of `teamMailboxRepository`, for instance:

```
interface TeamMailboxRepository {
    Mono<Void> teamMailboxesAdded(TeamMailbox teamMailbox);

    Mono<Void> teamMailboxesRemoved(TeamMailbox teamMailbox);
}
```

And add an implementation for the auto-complete....

**Review by chibenwa — CHANGES_REQUESTED** [review]

File: tmail-backend/mailbox/team-mailboxes/pom.xml [hunk 4]
```diff
@@ -14,6 +14,10 @@
     <name>Team-mail :: Mailbox :: Team-Mailboxes</name>
 
     <dependencies>
+        <dependency>
+            <groupId>${project.groupId}</groupId>
+            <artifactId>jmap-extensions</artifactId>
+        </dependency>
```
Comment (quantranhong1999) [inline tmail-backend/mailbox/team-mailboxes/pom.xml:20]: Well, this sucks and makes circular dependent.

Will need to resolve this.

Comment (chibenwa) [reply tmail-backend/mailbox/team-mailboxes/pom.xml:20]: Yes you can do that by defining a third party API

**Comment by quantranhong1999** [comment]
Rebased to solve conflicts.

File: tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxCallbackUtils.scala [hunk 5]
```diff
@@ -0,0 +1,26 @@
+package com.linagora.tmail.james.jmap.team.mailboxes
+
+import com.linagora.tmail.james.jmap.contact.{ContactFields, EmailAddressContactSearchEngine}
+import com.linagora.tmail.team.TeamMailbox
+import javax.inject.Inject
+import org.reactivestreams.Publisher
+import reactor.core.scala.publisher.SMono
+
+class TeamMailboxCallbackUtils @Inject()(contactSearchEngine: EmailAddressContactSearchEngine) {
```
Comment (chibenwa) [inline tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxCallbackUtils.scala:9]: Nicer.

But the name sucks.

And that is not yet a generic API with a multibinder.

File: tmail-backend/webadmin/webadmin-team-mailboxes/src/main/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutes.java [hunk 6]
```diff
@@ -62,13 +63,17 @@ public String getUsername() {
...
     private final DomainList domainList;
     private final JsonTransformer jsonTransformer;
+    private final TeamMailboxCallbackUtils teamMailboxCallback;
 
     @Inject
     public TeamMailboxManagementRoutes(TeamMailboxRepository teamMailboxRepository,
-                                       DomainList domainList, JsonTransformer jsonTransformer) {
+                                       DomainList domainList,
+                                       JsonTransformer jsonTransformer,
+                                       TeamMailboxCallbackUtils teamMailboxCallback) {
```
Comment (chibenwa) [inline tmail-backend/webadmin/webadmin-team-mailboxes/src/main/java/com/linagora/tmail/webadmin/TeamMailboxManagementRoutes.java:72]: No still not. The callbacks needs to be part of TeamMailboxesRepository. As a caller I should not need to worry and even know about it.

File: tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxExtensionBehaviourImpl.scala [hunk 7]
```diff
@@ -1,12 +1,12 @@
...
 
 import com.linagora.tmail.james.jmap.contact.{ContactFields, EmailAddressContactSearchEngine}
-import com.linagora.tmail.team.TeamMailbox
+import com.linagora.tmail.team.{TeamMailbox, TeamMailboxExtensionBehaviour}
 import javax.inject.Inject
 import org.reactivestreams.Publisher
 import reactor.core.scala.publisher.SMono
 
-class TeamMailboxCallbackUtils @Inject()(contactSearchEngine: EmailAddressContactSearchEngine) {
+class TeamMailboxExtensionBehaviourImpl @Inject()(contactSearchEngine: EmailAddressContactSearchEngine) extends TeamMailboxExtensionBehaviour {
```
Comment (quantranhong1999) [inline tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxExtensionBehaviourImpl.scala:9]: Thank you for the interface idea, that helped me solve the circular dependency issue.

I guess you want this to be even more modular (multiple behavior implementation e.g auto-complete, ...).
But at the moment there is limited extension behavior, so now I would prefer keeping this simple by aggregating behaviors into a single impl class.

If that is ok to you?

Comment (chibenwa) [inline tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxExtensionBehaviourImpl.scala:9]: TeamMailboxExtensionBehaviour => TeamMailboxCallback

TeamMailboxExtensionBehaviourImpl => TeamMailboxAutocompleteCallback

File: tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxJmapModule.scala [hunk 8]
```diff
@@ -13,5 +14,7 @@ class TeamMailboxJmapModule extends AbstractModule {
     Multibinder.newSetBinder(binder, classOf[Method])
       .addBinding()
       .to(classOf[TeamMailboxRevokeAccessMethod])
+
+    bind(classOf[TeamMailboxExtensionBehaviour]).to(classOf[TeamMailboxExtensionBehaviourImpl])
```
Comment (chibenwa) [inline tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxJmapModule.scala:18]: MultiBinder

File: tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala [hunk 9]
```diff
@@ -61,7 +60,8 @@ object TeamMailboxRepositoryImpl {
 }
 
 class TeamMailboxRepositoryImpl @Inject()(mailboxManager: MailboxManager,
-                                          subscriptionManager: SubscriptionManager) extends TeamMailboxRepository {
+                                          subscriptionManager: SubscriptionManager,
+                                          teamMailboxExtensionBehaviour: TeamMailboxExtensionBehaviour) extends TeamMailboxRepository {
```
Comment (chibenwa) [inline tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala:64]:
```suggestion
                                          teamMailboxExtensionBehaviour: Set[TeamMailboxExtensionBehaviour]) extends TeamMailboxRepository {
```

File: tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TMailCanSendFromTest.scala [hunk 10]
```diff
@@ -29,7 +29,7 @@ class TMailCanSendFromTest extends CanSendFromContract {
       integrationResources.getMailboxManager.getMapperFactory,
       integrationResources.getMailboxManager.getEventBus)
 
-    teamMailboxRepository = new TeamMailboxRepositoryImpl(integrationResources.getMailboxManager, subscriptionManager, new TeamMailboxExtensionBehaviourNoop)
+    teamMailboxRepository = new TeamMailboxRepositoryImpl(integrationResources.getMailboxManager, subscriptionManager, java.util.Set.of(new TeamMailboxCallbackNoop))
```
Comment (chibenwa) [inline tmail-backend/mailbox/team-mailboxes/src/test/scala/com/linagora/tmail/team/TMailCanSendFromTest.scala:32]: Use an import for java.util.Set (you can name it JavaSet to avoid classpath clahes)

**Review by chibenwa — APPROVED** [review]

**Comment by Arsnael** [comment]
```
[ERROR] Failures: 

[ERROR]   TeamMailboxRepositoryTest.removeMemberShouldUnSubscribeTeamMailbox:353 

Expecting

  [#TeamMailbox:team-mailbox@linagora.com:marketing.Sent]

not to contain

  [#TeamMailbox:team-mailbox@linagora.com:marketing,

    #TeamMailbox:team-mailbox@linagora.com:marketing.INBOX,

    #TeamMailbox:team-mailbox@linagora.com:marketing.Sent]

but found

  [#TeamMailbox:team-mailbox@linagora.com:marketing.Sent]
```
Likely related? :)

**Comment by quantranhong1999** [comment]
> [ERROR]   TeamMailboxRepositoryTest.removeMemberShouldUnSubscribeTeamMailbox:353 

At least not failed on my local yet. I would doubt this unstable test come from this commit rather than mine:
https://github.com/linagora/tmail-backend/commit/11af8c4b089fb3f0c46e62850253ccf94dd2e9eb

Will quickly check to see what I can do..

**Comment by quantranhong1999** [comment]
Yes, it is unstable:
image

**Comment by Arsnael** [comment]
Please try to find a way for this as well thanks :)

**Review by Arsnael — APPROVED** [review]

File: tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxAutocompleteCallback.scala [hunk 11]
```diff
@@ -0,0 +1,26 @@
...
+import com.linagora.tmail.james.jmap.contact.{ContactFields, EmailAddressContactSearchEngine}
+import com.linagora.tmail.team.{TeamMailbox, TeamMailboxCallback}
+import javax.inject.Inject
+import org.reactivestreams.Publisher
+import reactor.core.scala.publisher.SMono
+
+class TeamMailboxAutocompleteCallback @Inject()(contactSearchEngine: EmailAddressContactSearchEngine) extends TeamMailboxCallback {
+
+  def teamMailboxAdded(teamMailbox: TeamMailbox): Publisher[Void] = {
+    def indexDomainContact(): SMono[Unit] =
```
Comment (vttranlina) [inline tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxAutocompleteCallback.scala:12]: Q: Why do we need an extracted variable for it?
More readable?

File: tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala [hunk 12]
```diff
@@ -79,6 +82,10 @@ class TeamMailboxRepositoryImpl @Inject()(mailboxManager: MailboxManager,
         case Some(validationFailure) => SMono.error(TeamMailboxNameConflictException(validationFailure.errorMessage))
         case None => createDefaultMailboxReliably(teamMailbox, session)
       })
+      .`then`(SFlux.fromIterable(teamMailboxCallbackSetScala)
+        .flatMap(_.teamMailboxAdded(teamMailbox), ReactorUtils.DEFAULT_CONCURRENCY)
+        .collectSeq()
+        .`then`(SMono.empty))
```
Comment (vttranlina) [inline tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala:88]:
```suggestion
   .`then`())
```

File: tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala [hunk 13]
```diff
@@ -95,6 +102,10 @@ class TeamMailboxRepositoryImpl @Inject()(mailboxManager: MailboxManager,
 
   override def deleteTeamMailbox(teamMailbox: TeamMailbox): Publisher[Void] =
     deleteDefaultMailboxReliably(teamMailbox, createSession(teamMailbox))
+      .`then`(SFlux.fromIterable(teamMailboxCallbackSetScala)
+        .flatMap(_.teamMailboxRemoved(teamMailbox), ReactorUtils.DEFAULT_CONCURRENCY)
+        .collectSeq()
+        .`then`(SMono.empty))
```
Comment (vttranlina) [inline tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala:108]:
```suggestion
.`then`())
```

File: tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala (hunk 12 above)
Comment (quantranhong1999) [reply tmail-backend/mailbox/team-mailboxes/src/main/scala/com/linagora/tmail/team/TeamMailboxRepository.scala:88]: The original code is to bypass the compiler. Otherwise we have:
```
 found   : reactor.core.scala.publisher.SMono[Unit]
 required: reactor.core.scala.publisher.SMono[Void]
        .`then`())
```

File: tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxAutocompleteCallback.scala (hunk 11 above)
Comment (quantranhong1999) [reply tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/team/mailboxes/TeamMailboxAutocompleteCallback.scala]: I should shorten this actually.

**Review by vttranlina — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]
